from typing import List, Optional

class CollectionHandle:
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def append_record(self, doc: bytes) -> int: ...
    def read_record(self, offset: int) -> Optional[bytes]: ...
    def tombstone_record(self, offset: int) -> None: ...
    def next_live_offset(self, prev: int) -> Optional[int]: ...
    def live_count(self) -> int: ...
    def data_end(self) -> int: ...

class IndexHandle:
    field_path: str
    unique: bool
    descending: bool

    def close(self) -> None: ...
    def flush(self) -> None: ...
    def insert(self, key: bytes, record_offset: int) -> None: ...
    def lookup(self, key: bytes) -> List[int]: ...
    def range(
        self,
        low: Optional[bytes],
        low_inclusive: bool,
        high: Optional[bytes],
        high_inclusive: bool,
    ) -> List[int]: ...
    def delete_entry(self, key: bytes, record_offset: int) -> None: ...

def open_collection(path: str) -> CollectionHandle: ...
def create_index_file(
    path: str,
    field_path: str,
    key_type_tag: int,
    unique: bool,
    descending: bool,
) -> IndexHandle: ...
def open_index_file(path: str) -> IndexHandle: ...
